# Homebrew formula for `ripple`, a headless deep-agent CLI built on DeepAgents.
#
# Kept in-repo for local installs; not (yet) published to a tap. Install it directly from a clone:
#
#   brew install --HEAD ./Formula/ripple.rb
#
# Building resolves Swift package dependencies (network) and uses Xcode's build system, so if
# Homebrew's build sandbox blocks it, prefix with `HOMEBREW_NO_SANDBOX=1`.
#
# When a release is cut, add a `url`/`sha256` (a GitHub tarball of the tag) and a `version` so
# `brew install ripple` works without `--HEAD`.
class Ripple < Formula
  desc "Headless deep-agent CLI (on-device MLX agents)"
  homepage "https://github.com/dsaad68/ripple"
  head "https://github.com/dsaad68/ripple.git", branch: "main"
  license "MIT"

  depends_on xcode: ["26.0", :build]
  depends_on arch: :arm64
  # macOS 26+ (Tahoe); the Ripple package targets .macOS("26.0").
  depends_on macos: :tahoe

  def install
    # Build with xcodebuild rather than `swift build`: only Xcode's build system emits MLX's
    # Metal shader library (default.metallib), which the CLI needs at runtime. xcodebuild
    # co-locates it (in mlx-swift_Cmlx.bundle) and the other SwiftPM resource bundles next to
    # the binary. The `ripple` scheme is auto-generated by SwiftPM for the executable product.
    xcodebuild "-scheme", "ripple",
               "-configuration", "Release",
               "-destination", "platform=macOS",
               "-derivedDataPath", "build",
               "-skipPackagePluginValidation",
               "build"

    products = "build/Build/Products/Release"
    metallib = "#{products}/mlx-swift_Cmlx.bundle/Contents/Resources/default.metallib"
    odie "MLX metallib was not produced at #{metallib}" unless File.exist?(metallib)

    # The binary resolves its resources from the *.bundle co-located beside it, so keep them
    # together in libexec and shim a thin launcher into bin.
    libexec.install "#{products}/ripple"
    libexec.install Dir["#{products}/*.bundle"]
    (bin/"ripple").write_env_script libexec/"ripple", {}
  end

  def caveats
    <<~EOS
      ripple runs a deep agent on-device with MLX (Apple Silicon, macOS 26+).

      Models come from your local Hugging Face cache; ones that aren't already cached are skipped
      rather than downloaded. Pre-fetch a planner first, e.g.:
        hf download LiquidAI/LFM2.5-1.2B-Instruct-MLX-bf16

      The Apple Notes tools ask for Automation permission on first use
      (System Settings > Privacy & Security > Automation).

      Usage:
        ripple chat                interactive deep-agent REPL
        ripple run <scenarios>     headless scenario harness
    EOS
  end

  test do
    assert_match "usage:", shell_output("#{bin}/ripple --help 2>&1")
  end
end
